language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-hipchat-plugin-2.0.1.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-hipchat-plugin
  api_key:
    secure:
      secure: XMPXusk3bNGv4Bz99ujBdO4+JBtGQAhZfICmPq3nEr/7RRdKWQzG+/qTVdmp42y61kP/iWnMmdfVHHvs/QzzXDu/cjtgZEC1rmaMx9B6CXmISGj2vnHje4VvjGKZJhYI6RnfebEP1ElbMCZVKYcFWJ/Edmyt4Rz7m7RApTW6umU=
notifications:
  hipchat:
    rooms:
      secure: PokzODAegGur+mie4WJo9qm5OqFNsFruxOLJ/PffSLcx+BOJlqUppjmPu4l+8O11FdggJ+Kw4UorQQGx/axoUYUPlkglyPiOs+g6gb/gC+CeXLyK5PRbAepn23mkO9vxDRtgwd0JU0L87DcEiKK1DlCJ1uT+uiyTcJa+VClaSuM=
