language: java
sudo: false
deploy:
  provider: releases
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-hipchat-plugin
  api_key:
    secure: hZupYLg6WsRiFHBghFNl8K/a/LXozLtAlGppIgiVzT8wlzjivRpKyL8DjksJUyyyiODUQ5MOnCtHDnX+x/u2E9M0NCfDfrrKuwwkgfGMj6sfGYA8K4l9nO5j9/LLj24mjph1jWxtJLq6Hrs1eWXiqoK726xa0VV27a4sLQLHyhs=
notifications:
  hipchat:
    rooms:
      secure: PokzODAegGur+mie4WJo9qm5OqFNsFruxOLJ/PffSLcx+BOJlqUppjmPu4l+8O11FdggJ+Kw4UorQQGx/axoUYUPlkglyPiOs+g6gb/gC+CeXLyK5PRbAepn23mkO9vxDRtgwd0JU0L87DcEiKK1DlCJ1uT+uiyTcJa+VClaSuM=
